const SRC_BASE_PATH = './src';
const TYPES_FILE_PATH = 'interfaces.ts';
const SUMMARY_API_URL = 'https://corona.ps/API/summary';
const DETAILS_API_URL = 'https://corona.ps/API/cases';
const CRON_JOB_NOTATION_EVERY_30_MIN = '*/1 * * * *';
const GOVERNORATE_SUMMARY_URL = 'https://corona.ps/API/governorates';

/** Firebase Firestore Collections */
const CASES_COLLECTION_REF = 'CASES';
const SUMMARIES_COLLECTION_REF = 'SUMMARIES';
const GOVERNORATES_COLLECTION_REF = 'GOVERNORATES';

export {
  SRC_BASE_PATH,
  TYPES_FILE_PATH,
  SUMMARY_API_URL,
  DETAILS_API_URL,
  CASES_COLLECTION_REF,
  GOVERNORATE_SUMMARY_URL,
  SUMMARIES_COLLECTION_REF,
  GOVERNORATES_COLLECTION_REF,
  CRON_JOB_NOTATION_EVERY_30_MIN,
};
